### ISSUE TITLE
Gearman doesn't apply parameters in config file on Ubuntu 14.04.2 x86_64

### ISSUE THREAD

**Issue by PaulDenton** [saz/puppet-gearman#12]
Here's output of ps right after catalog run is finished:

```
gearman  25837  0.0  0.2 481508  9800 ?        Ssl  13:38   0:00 /usr/sbin/gearmand --log-file=/var/log/gearman-job-server/gearman.log
```

And contents of `/etc/default/gearman-job-server`:

```
PARAMS="--backlog=32 \
--job-retries=0 \
--port=4730 \
--listen=127.0.0.1 \
--threads=4 \
--file-descriptors=1024 \
--worker-wakeup=0 \
"
```

Parameters are applied only if the service is started via init script:
`sudo /etc/init.d/gearman-job-server start`

```
gearman  24176  0.0  0.0 489940  3568 ?        Ssl  13:35   0:00 /usr/sbin/gearmand --pid-file=/var/run/gearman/gearmand.pid --user=gearman --daemon --log-file=/var/log/gearman-job-server/gearman.log --backlog=32 --job-retries=0 --port=4730 --listen=127.0.0.1 --threads=4 --file-descriptors=1024 --worker-wakeup=0
```

**Comment by kimegede** [comment]
Is a bug report filled out to the Gearman team?
Just experienced the same.

**Comment by saz** [comment]
I'm sorry, but this is not an issue with this module, but with the behavior of parameters for gearman. Maybe this has changed today, but I'm not sure about that.
